> train = read.csv(file.choose())
> test = read.csv(file.choose())
> train = na.omit(train)
> attach(train)
> mod = lm(price2013~state)
> summary(mod)
> options(max.print = 10000)
> mod1 = lm(price2013~state+county)
> summary(mod)
> train1 = read.csv(file.choose())
> detach(train)
> attach(train1)
> mod2 = lm(price2013~zip+ state+county + poverty + price2007)
> summary(mod2)
> test$price2013 = rep(0,1063)
> test$price2013 = predict(mod2, newdata = test)
> submit = data.frame(id = test$id, prediction = test$price2013)
> write.csv(submit, file= "prediction.csv", row.names = FALSE)